### ISSUE TITLE
Missing BioMotionLab_NTroje from AMASS Dataset

### ISSUE THREAD

**Issue by bryanbocao** [FIGLAB/IMUPoser#12]
```BioMotionLab_NTroje``` is missing from the current AMASS dataset download website (https://amass.is.tue.mpg.de/download.php). Would that be fine? Or it is not a big issue that the model may have less training data and less diverse dataset?

**Comment by VimalMollyn** [comment]
AMASS has had updates since we released our code. I'm not exactly sure which datasets are different, but you should be able to get comparable results with the datasets currently available in AMASS.
