### ISSUE TITLE
devices

### ISSUE THREAD

**Issue by whl-007** [FIGLAB/IMUPoser#3]
I just finished reading your article where you used three types of devices - a phone, a watch, and headphones to reconstruct human motion. However, I didn't see any results regarding the use of only one pair of headphones. Therefore, I wanted to ask how effective it is to reconstruct human motion using only one pair of headphones. Do you think it would be possible to accurately detect the posture of the whole body, including hands and legs, if I use only one pair of headphones? 
Another question I have is, you mentioned using only Apple's phone, watch, and headphones, and transferring their IMU data to the computer. Would it be possible to use other devices like Huawei or Samsung phones? 
Can you please clarify this for me?Thank you very much.

**Comment by VimalMollyn** [comment]
Hi! Figure 6 in our paper shows how performance changes across various device combinations. In particular, the MPJVE of full body reconstruction using only earbuds is 17.3 and 19.9 cm on the DIP-IMU and IMUPoser datasets. In practice, we observe that using just the earbuds is decently accurate for tracking motions like walking and squatting (where the motion of the limbs is predictable) and not great for more complex motions.

As for using other devices, as long as the devices have IMUs they should be able to work with IMUPoser!
