### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by whl-007** [FIGLAB/IMUPoser#4]
When reproducing your project, I found that I don't know where to download the models and datasets in your [config.py](http://config.py/) file, especially for the src/imuposer/smpl/model.pkl file. I noticed that Transpose is using the files from male and female folders. Could you please tell me if you are using the files from male folder and provide me with the download links?
![image](https://github.com/FIGLAB/IMUPoser/assets/120098257/48ffc071-7a0e-4f89-a2da-170cda0bad34)

**Comment by whl-007** [comment]
Hello，I find another question when I Conduct an Experiment.How to calibratie the IMU to the Vicon optical motion capture system？
I am using retro-reflective markers and the Vicon optical motion capture system to capture ground-truth. I have a specific question: do you use an optical motion capture system to capture ground-truth? When calibrating the IMU, is it necessary to align it with the x, y, and z axes of the optical motion capture system? If so, wouldn't manual alignment introduce a lot of error? Or have you used other special methods (such as T-pose) to solve some of these problems? However, I cannot find a tutorial on the system online. Can you recommend one to me? I would be very grateful if you could answer my question.

**Comment by wsascha** [comment]
Hi there :wave:
Can you make an estimate on when data will be available? – Is there any chance that this would be permissively licensed?

**Comment by VimalMollyn** [comment]
> When reproducing your project, I found that I don't know where to download the models and datasets in your [config.py](http://config.py/) file, especially for the src/imuposer/smpl/model.pkl file. I noticed that Transpose is using the files from male and female folders. Could you please tell me if you are using the files from male folder and provide me with the download links? ![image](https://user-images.githubusercontent.com/120098257/244636993-48ffc071-7a0e-4f89-a2da-170cda0bad34.png)

Hi, I've updated the README to help with this.

**Comment by whl-007** [comment]
I just want to try it now.If I can do it,I Will tell you.
        
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Sascha ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/4/2023 14:53
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [FIGLAB/IMUPoser] Datasets (Issue #4)
        
      
    
  

Hi there 👋 !
Can you make an estiimate on when data will be available? – Is there any chance that this would be permissively licensed?

**Comment by whl-007** [comment]
Thank you very much!
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Vimal ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/4/2023 03:18
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [FIGLAB/IMUPoser] Datasets (Issue #4)
        
      
    
  


When reproducing your project, I found that I don't know where to download the models and datasets in your config.py file, especially for the src/imuposer/smpl/model.pkl file. I noticed that Transpose is using the files from male and female folders. Could you please tell me if you are using the files from male folder and provide me with the download links? 

Hi, I've updated the README to help with this.
