### ISSUE TITLE
When will the dataset be released?

### ISSUE THREAD

**Issue by cheng-haha** [FIGLAB/IMUPoser#5]
This work is very cool and could be influential for future researchers. Releasing the dataset promptly could potentially increase the citation count for this paper.

**Comment by jianwang-mpi** [comment]
When will the dataset be released?

**Comment by VimalMollyn** [comment]
Hi, thanks for your interest! We've released the dataset [here](https://www.dropbox.com/s/myq9k0x9i5waphn/imuposer_dataset.zip?dl=0). I've also updated the README with more instructions and a quick walkthrough.
