### ISSUE TITLE
how to get the data of devices

### ISSUE THREAD

**Issue by LannnSun** [FIGLAB/IMUPoser#6]
I'm very interested in your article where you used three types of devices - a phone, a watch, and earbuds to reconstruct human motion. But I have not found any learning resources to get the IMU data of these three devices. Therefore, I would like to ask you how to get the data of them. I hope I haven't disturbed you. Thank you very much.

**Comment by VimalMollyn** [comment]
Apologies on the late reply. Please check out the new [live](https://github.com/FIGLAB/IMUPoser/tree/main/live) folder for more instructions. Hope that helps!
